- name: create directory /etc/httpd/conf.d
  file: path=/etc/httpd/conf.d state=directory owner=root group=root mode=0755

- copy: src=servername.conf dest=/etc/httpd/conf.d/servername.conf owner=root mode=0644